baseURL = 'https://benjamin-philip.github.io/sicp/'
languageCode = 'en-us'
title = 'SICP'
disqusShortname = "spf13"       # Force giscus

[params]
  description = 'My latest stab at reading that legendary book by Gerald Jay Sussman and Hal Abelson.'
  themeColor = 'theme-base-08'

  [params.author]
    name = "Benjamin Philip"
    email = "benjamin.philip495@gmail.com"

[Menus]
  main = [
    {Name = "About", URL = "/about"},
    {Name = "Book", URL = "https://web.mit.edu/6.001/6.037/sicp.pdf"},
    {Name = "MIT OCW", URL = "https://ocw.mit.edu/courses/6-001-structure-and-interpretation-of-computer-programs-spring-2005/"},
    {Name = "GitHub", URL = "https://github.com/Benjamin-Philip/sicp"},
  ]

[outputs]
  home = ["HTML", "RSS", "ATOM"]
  section = ["HTML", "RSS", "ATOM"]
  taxonomy = ["HTML", "RSS", "ATOM"]

[module]
  [[module.imports]]
    path = 'github.com/spf13/hyde'

  [[module.imports]]
    path = 'github.com/kaushalmodi/hugo-atom-feed'
