#+title: About
#+date: 2025-07-08
* Introduction
"Structure and Interpretation of Computer Programs" is a text that was used in a
course at MIT as an introduction to Computer Science. Over the years it has
built up a reputation as the rite of passage for enthusiastic students and
bloggers to become Computer Science wizards, if they finish reading it that is. You can find a PDF of the book
[[https://web.mit.edu/6.001/6.037/sicp.pdf][here]], along with the associated MIT OpenCourseWare [[https://ocw.mit.edu/courses/6-001-structure-and-interpretation-of-computer-programs-spring-2005/][course]].

When I read a (good) book with exercises, I like to keep a log with all my
answers to those exercises. I feel like I've not got the best of the book
otherwise. That's what this website is. Ideally, I'd like to take notes, but
this book is so vast that if I did that, I would never finish.

This is not the first time I've tried to read this book. That was what I did
during the COVID pandemic, from 2020 up until 2022, starting at the age of 13. Needless to
say, my writing was not great and I didn't follow a lot of the maths. You can
find the old site [[https://benjamin-philip.github.io/sicp-archive/][here]]. Five years later, at the age of 18, this is just my
latest attempt. Maybe second time lucky?
* Local setup
Since Fedora doesn't package [[https://www.gnu.org/software/mit-scheme/][MIT Scheme]], I'm using [[https://racket-lang.org/][Racket]] instead along with the
[[https://docs.racket-lang.org/sicp-manual/index.html][SICP package]]. To streamline the literate style, I'm using [[https://www.gnu.org/software/emacs/][Emacs]] along with [[https://orgmode.org/worg/org-contrib/babel/intro.html][Org
Babel]] so that I can iterate on both my prose and my code seamlessly from just my
editor in a single buffer.
* Website setup
This website is generated by [[https://gohugo.io][Hugo]], with the [[https://github.com/spf13/hyde][Hyde]] theme. It's hosted on [[https://pages.github.com/][GitHub
Pages]] in [[https://github.com/Benjamin-Philip/sicp][this git repository]]. I'm using [[https://giscus.app][giscus]] for comments, and [[https://umami.is][umami]] for analytics.
